format:
  pdf:
    latex-auto-install: false
    use-rsvg-convert: true
    documentclass: scrartcl
    papersize: a4
    colorlinks: true
    fig-width: 5
    fig-height: 4
    mainfont: Times New Roman
    sansfont: Times New Roman
    monofont: Noto Sans Mono Black
    top-level-division: section
    toc-depth: 2
    number-depth: 3
    include-in-header:
      - text: |
         \usepackage{fontspec}
         \usepackage{fontawesome5}
