# Общие требования {.unnumbered}

Согласно SRS приложение должно быть реализовано на следующем стеке технологий и реализовано в среде.

## Operating Environment

Проект представляет собой клиент-серверное веб приложение.

-   Сервер приложений Tomcat версия 11.0 и выше
-   База данных PostgreSQL версия 18 и выше
-   JDK верия 25 и Java Language версия 25 и выше
-   Операционная система любая ОС, поддерживающая указанные выше технологии.

## Design and Implementation Constraints

-   **Бэкенд:** Приложение должно быть реализовано на Java с использованием спецификаций Jakarta EE (Servlet, JSP), допустимо использование (JPA, Bean Validation).
-   **Персистентность:** Для доступа к данным должен использоваться JDBC и RAW запросы. Допустимо использование JPA (Hibernate в качестве реализации) для работы с СУБД PostgreSQL.
-   **Веб-интерфейс:** Для создания пользовательского интерфейса должны использоваться JSP/Servlets JavaServer Faces (JSF). Допускается использование JavaServer Faces (JSF).


Как записываются фичи, приоритет их реализации

## Структура SRS

IEEE Std 830-1998

Высокоуровневый перечень основных функций, которые будет предоставлять продукт:

Можно предложить свою тему проекта. Обязательным требованием явлется предоставление и согласование SRS с преподавателем.